Add instanseg
bilayer-containers/bilayers pull request #49
Opened 2024-09-25 14:59 UTC by bethac07

2024-10-05 02:05 UTC, gnodar01 commented
I've added a dockerfile for both non-cuda and cuda. They both work on my intel macbook. Both images have been pushed to dockerhub.

Would be nice to have someone test the cuda image on an actual nvidia machine, to see if GPU mode works.

I did both after all because of the massive size difference. Compressed, the non-cuda is 2.33 GB and the cuda image is 7.97 GB. I have no idea why there is that large of a discrepancy. Yes they use different bases (but still on Ubuntu 22.04), and cuda-compiled versions of various packages, but I wouldn't have expected THAT much of a difference.

`nvidia/cuda:12.3.1-base-ubuntu22.04` is 30.82 MB, and `ubuntu:jammy` is 28.17 MB.

2024-10-07 13:08 UTC, bethac07 commented
Thanks man, nice work!

I finally also traced the issue I was seeing on my side, it is a "Beth didn't upgrade her computer in a long time and there's a now-patched bug in Rosetta" :shame: :shame: :shame:

2024-10-31 12:31 UTC, gnodar01 commented
Is it intentional to have the rather large `_build` folder, containing docs here in this PR (or in general not gitignored)?

2024-10-31 15:34 UTC, rajavishah commented
Ohh sorry, forgot to insert the folder name in gitignore! - Will fix that in next commit

2024-11-18 15:23 UTC, rajavishah commented
Resolves #77, and instanseg algorithm 

@gnodar01 feel free to review

2024-12-12 18:15 UTC, gnodar01 requested changes
I think at this point we can get rid of `Dockerfile_conda`, `Dockerfile_mamba`, and `Dockerfile_working_mamba`

2024-12-12 18:26 UTC, gnodar01 commented on noxfile.py
> +            session.run('docker', 'pull', "--platform", "linux/amd64", "bilayer/instanseg:1.0.2")
Shouldn't be hardcoding "bilayer/instanseg" here.

2024-12-12 18:34 UTC, gnodar01 reviewed
Needs to be rebased on main as well, with conflicts.

2024-12-12 21:30 UTC, bethac07 commented
Closing for now, as it's seeming more likely we want to probably only cherry pick very small parts of this branch out for real, and other parts (like the various dockerfiles) will only be for documentation. Please don't delete the branch though until that work is done.

2024-12-12 21:30 UTC, closed without merging