Fixing some recently noticed problems
bilayer-containers/bilayers pull request #54
Opened 2024-10-04 19:34 UTC by rajavishah

Recently, I encountered some issues - 

1. When running the `cli_command` on clicking `on_submit()`, I attached screenshot error. It was resolved by installing FastAPI to Gradio.Dockerfile, although I'm not sure why `Pydantic` would need `FastAPI`. The issue seems to be resolved, but I don't have a clear understanding of why this works. Do you have any alternative solutions, @gnodar01?
<img width="833" alt="img-err" src="https://github.com/user-attachments/assets/5d17069f-bb55-4352-b0e5-6d239d3f0ae1">

2. And since our function [here](https://github.com/bilayer-containers/bilayers/blob/main/src/Build/parse/gradio_template.py.j2#L290-L300) requires the output of the subprocess, we need to capture it by changing stdout=subprocess.None to stdout=subprocess.PIPE. Without this change, when a custom folder_name is provided for saving the output, Nothing is displayed (no files are returned) in the Gradio interface
3. @gnodar01 Have you mapped to a port other than `-p 8000:7878` while running the Docker image, and if so, is Gradio still able to run and produce the correct output? For me it's not
<img width="1630" alt="Screenshot 2024-10-04 at 3 30 25 PM" src="https://github.com/user-attachments/assets/68b1e002-302d-4f9f-ac77-bb9faa6f108c">
<img width="445" alt="Screenshot 2024-10-04 at 3 30 47 PM" src="https://github.com/user-attachments/assets/7b3dbe2c-cdf9-41d3-baa4-77e366611fe8">

Here, I was not able to get `--save_flows` and `--save_txt` 's outputs

2024-10-04 20:47 UTC, gnodar01 commented
Please copy-paste stack traces, instead of screenshots. That way I can copy-paste it myself when googling the error.

2024-10-04 20:50 UTC, gnodar01 commented
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pydantic/type_adapter.py", line 210, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File "/opt/conda/lib/python3.9/site-packages/pydantic/type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__
```

2024-10-04 20:54 UTC, gnodar01 commented
It looks like you just need to bump Gradio's version, not Fast API, [see here](https://github.com/C0untFloyd/roop-unleashed/discussions/887)

2024-10-04 20:57 UTC, gnodar01 commented
@rajavishah Is this PR actually ready for review? The changes in the code do not match up with the description given. If ready for review, please leave a more informative description detailing what has been changed and why, and which issues the changes correspond to.

2024-10-04 21:13 UTC, gnodar01 commented
> But it has literally 2 minor one-liner

Got it. It had a bunch of commits since it was branched off the prior PR. Let's not stack PRs if we can avoid it, otherwise I have no way of knowing what changes are specific to this PR. I've rebased on main now that the other PRs are merged.

2024-10-04 21:15 UTC, gnodar01 requested changes
It looks like you just need to bump Gradio's version, not Fast API, [see here](https://github.com/C0untFloyd/roop-unleashed/discussions/887)

2024-10-04 21:16 UTC, rajavishah commented
> Let's try bumping gradio instead.

Yes, I think bumping gradio's version working. I'm trying, could you check slack?

2024-10-04 22:26 UTC, rajavishah commented
> It looks like you just need to bump Gradio's version, not Fast API, [see here](https://github.com/C0untFloyd/roop-unleashed/discussions/887)

Okay, this works, tysm! I think we should reject this entire PR since it builds on top of another PR. Since it only involves a version update for Gradio, we can consider accepting it along with future new PRs

2024-10-04 23:26 UTC, gnodar01 commented
> since it builds on top of another PR

it no longer does, from above comment:

> I've rebased on main now that the other PRs are merged.

You can see that if you look at the "Files Changed" tab, which now only have the two changes, or that the commits have now been replaced with: 

![Screenshot 2024-10-04 at 7 25 35 PM](https://github.com/user-attachments/assets/1e605739-9a6a-4140-be77-1a93e48fbeb1)

2024-10-04 23:27 UTC, gnodar01 commented
> Since it only involves a version update for Gradio

The preference is that PRs are small, so this is a good thing. Let's keep it.

2024-10-07 12:51 UTC, rajavishah commented
Removed fast-API and upgraded the version of Gradio and Gradio-client

2024-10-15 21:24 UTC, gnodar01 approved these changes

2024-10-15 21:24 UTC, merged