Threshold works with cli_tags (custom threshold.py)
bilayer-containers/bilayers pull request #57
Opened 2024-10-15 19:52 UTC by rajavishah

**The current PR focuses on fixing/resolving -** 
1. Threshold should work seamlessly using cli_tag
    [details]: Previously, threshold algorithm was dependent on the function rather than cli_tag. Now, `threshold.py` is tweaked to have it's own `cli_tag`. 
2. `gradio` and `gradio-client` version updates - it's more advanced than one updated [here](https://github.com/bilayer-containers/bilayers/pull/54) 
4. At `build_docker.sh` file it provides both algorithm and interface names - [see here](https://github.com/bilayer-containers/bilayers/blob/threshold_fix/build_docker.sh#L7-L8)
5. noxsession - `build_algorithm` logic is updated in terms of it'll always look for docker-image on DockerHub if not available then build's image from local Dockerfile (In short logic is swapped - previously, it was prioritizing the build from local Dockerfile and now it's prioritizing pulling the available docker-image from dockerHub) - [here](https://github.com/bilayer-containers/bilayers/blob/threshold_fix/noxfile.py#L37-L74)
6.  noxsession - `build_interface` naming convention of each final docker-image holding `algorithm X interface` is updated [here](https://github.com/bilayer-containers/bilayers/blob/threshold_fix/noxfile.py#L86) - hence, naming conflicts can be avoided

**Still at Threshold algorithm problem persists -** 
1. `threshold_inference X jupyter` whilst the output_folder is same as the input_folder, it replicates the analysis on the generated_output. so, in a way it produces one extra output!

2024-10-16 16:33 UTC, gnodar01 requested changes
Needs to have conflicts resolved, on rebase with main

2024-10-18 17:45 UTC, rajavishah commented
Fixed the problem of #58
Read the comment on #58 to see the details.

@gnodar01 feel free to review at your convenience

2024-11-06 13:40 UTC, gnodar01 approved these changes

2024-11-06 13:40 UTC, gnodar01 approved these changes

2024-11-06 13:40 UTC, merged