Updated input_outputs
bilayer-containers/bilayers pull request #85
Opened 2024-12-13 18:29 UTC by rajavishah

2024-12-13 22:26 UTC, rajavishah commented
In a way ready for review with updated inputs, outputs. for details read #80 

Documentation isn't greatly updated. May need to refine that

2025-02-10 20:42 UTC, rajavishah commented
Resolves #80, #86, #29 

This PR is ready for review. What it does?
- updated code that handles `inputs`, `outputs` and remove `results` section
- Type Annotations for the current code. I'm skeptical about [this](https://github.com/bilayer-containers/bilayers/blob/updated_ip_op/src/algorithms/classical_segmentation/classical_segmentation.py#L51) annotation - could you please verify?
- Updated Docs

2025-02-21 16:35 UTC, gnodar01 reviewed
`Optional[<type>]` is deprecated as of python 3.8. We should go back to `<type> | None`

2025-02-21 16:51 UTC, gnodar01 reviewed
Occurences of `List[<type>]` are deprecated as of python 3.9. Replace with `list<type>` instead.

2025-02-21 17:15 UTC, gnodar01 reviewed
Occurences of `Dict` type annotations are deprecated in python 3.9, replace with `dict`

2025-02-21 17:15 UTC, gnodar01 commented on src/algorithms/classical_segmentation/classical_segmentation.py
> +        labeled_image: NDArray[Any] = skimage.measure.label(th_image)
I'm getting a type error here, I think because `skimage.measure.label` optionally returns a `tuple`. We should explicitly ignore with a comment stating that we know a tuple won't be returned since we're not using `return_num`

2025-02-21 17:15 UTC, gnodar01 commented on src/algorithms/classical_segmentation/Dockerfile
> +CMD ["python"]
Shouldn't have deleted the line break. Always leave a single newline at the end of files (code, text, config, etc). It's a POSIX requirement, among other reasons. See: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2025-02-21 17:18 UTC, gnodar01 reviewed
Replace occureces of `Tuple` type annotations with `tuple`

2025-02-21 17:18 UTC, gnodar01 commented on src/build/parse/jupyter_shell_command_template.py.j2
> +    print(f"Full Stack Trace:\n{error_message}")
Keep newline.

2025-02-21 17:18 UTC, gnodar01 commented on src/build/parse/jupyter_template.py.j2
> +    print("Hello World")
keep newline

2025-02-21 17:21 UTC, gnodar01 requested changes
In the future let's aim to always separate cosmetic changes (type annotations), and  changes in behaviour (inputs and outputs) into separate PRs.

2025-02-27 16:31 UTC, rajavishah commented
Merge #94 prior merging this to main

2025-03-14 16:36 UTC, gnodar01 approved these changes

2025-03-18 18:36 UTC, merged